FROM debian:latest

RUN apt-get update && apt-get install -y \
    openssh-server \
    sudo \
    systemctl

RUN useradd -ms /bin/bash node && echo 'node:nodepass' | chpasswd && adduser node sudo
RUN echo "node ALL=(ALL) NOPASSWD:ALL" >> /etc/sudoers
# SSH setup
RUN mkdir /var/run/sshd
RUN echo "PermitRootLogin yes" >> /etc/ssh/sshd_config
RUN echo "PasswordAuthentication yes" >> /etc/ssh/sshd_config

EXPOSE 22
CMD ["/usr/sbin/sshd", "-D"]