- name: Install docker
  hosts: all
  become: true
  tasks:
    - name: apt update  
      ansible.builtin.apt:
        update-cache: yes

    - name: Descargar script de instalación de Docker
      ansible.builtin.get_url:
        url: https://get.docker.com
        dest: /tmp/get-docker.sh
        mode: '0755'
    
    - name: Instalar Docker
      ansible.builtin.shell: /tmp/get-docker.sh

    - name: Comprobar instalación de Docker
      ansible.builtin.command: docker --version
      register: docker_version

    - name: Mostrar versión de Docker
      ansible.builtin.debug:
        msg: "Docker version: {{ docker_version.stdout }}"
